[package]
name = "viaems-fpga-tb"
version = "0.1.0"
edition = "2021"

[dependencies]
gumdrop = { version = "*" }
nusb = "*"
futures-lite = "*"

[profile.release]
opt-level = 3
lto = true

[[bin]]
name = "viaems-fpga-tb"
path = "src/main.rs"

[[bin]]
name = "viaems-target-proxy"
path = "src/proxy.rs"
